# Generated by Django 3.2.8 on 2022-02-13 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('data_agendada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data agendada')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da criacao ')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabecalho', models.CharField(max_length=300)),
                ('texo_span', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('lista_produtos', models.TextField(verbose_name='Lista de produtos')),
                ('total', models.PositiveSmallIntegerField(verbose_name='Valor total da compra')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
