# Generated by Django 3.2.8 on 2022-02-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.FloatField(default=0.0),
        ),
    ]
