# Generated by Django 3.2.8 on 2022-02-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0002_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='idade',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='telefone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='corpo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='distrito',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='morada',
            field=models.CharField(default='Sem morada', max_length=300),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='telefone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
