# Generated by Django 3.2.8 on 2022-02-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0003_auto_20220213_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='texo_span',
            new_name='texto_span',
        ),
    ]
