# Generated by Django 3.2.8 on 2022-02-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0006_agendamento_morada'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
