# Generated by Django 3.2.8 on 2022-02-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0008_auto_20220217_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=False),
        ),
    ]
