# Generated by Django 3.2.8 on 2022-02-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0010_alter_produto_disponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
