# Generated by Django 3.2.8 on 2022-02-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0012_alter_produto_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='url_imagem',
            field=models.URLField(default='https://images.pexels.com/photos/946727/pexels-photo-946727.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'),
        ),
    ]
